# Generated by Django 2.0.2 on 2018-02-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UkName', models.CharField(blank=True, max_length=300, null=True)),
                ('EnName', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterPiece', models.ImageField(upload_to='Masterpieces')),
                ('UkName', models.CharField(blank=True, max_length=300, null=True)),
                ('EnName', models.CharField(blank=True, max_length=300, null=True)),
                ('UkDescription', models.TextField(blank=True, null=True)),
                ('EnDescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UkName', models.CharField(blank=True, max_length=300, null=True)),
                ('EnName', models.CharField(blank=True, max_length=300, null=True)),
                ('Block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWorks.Block')),
            ],
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='SubBlock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWorks.SubBlock'),
        ),
    ]
