# Generated by Django 2.0.4 on 2018-05-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWorks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='Block_URL',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
