# Generated by Django 2.0.4 on 2018-06-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWorks', '0002_block_block_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UkName', models.CharField(blank=True, max_length=300, null=True)),
                ('EnName', models.CharField(blank=True, max_length=300, null=True)),
                ('SubBlock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWorks.SubBlock')),
            ],
        ),
    ]
