# Generated by Django 2.0.4 on 2018-06-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWorks', '0003_subsubblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpiece',
            name='SubSubBlock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWorks.SubSubBlock'),
        ),
    ]
