# Generated by Django 2.0.4 on 2018-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWorks', '0004_masterpiece_subsubblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpiece',
            name='UkName',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
