# Generated by Django 2.0.2 on 2018-02-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterPiece', models.ImageField(upload_to='Masterpieces')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PainterApp.Block')),
            ],
        ),
    ]
