# Generated by Django 2.0.2 on 2018-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PainterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='Name',
            new_name='EnName',
        ),
        migrations.RenameField(
            model_name='masterpiece',
            old_name='Name',
            new_name='EnName',
        ),
        migrations.AddField(
            model_name='block',
            name='UkName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='EnDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='UkDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterpiece',
            name='UkName',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
