# Generated by Django 2.0.4 on 2018-05-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UkName', models.CharField(blank=True, max_length=300, null=True)),
                ('EngName', models.CharField(blank=True, max_length=300, null=True)),
                ('UkDescription', models.CharField(blank=True, max_length=300, null=True)),
                ('EngDescription', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectureImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='Lectures')),
                ('Lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lectures.Lecture')),
            ],
        ),
    ]
