# Generated by Django 2.0.4 on 2018-06-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lectures', '0002_auto_20180520_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.URLField()),
                ('Lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Lectures.Lecture')),
            ],
        ),
    ]
